### ISSUE TITLE
Unable to install in pumukit 2.2.0

### ISSUE THREAD

**Issue by mliradelc** [teltek/PumukitPaellaPlayerBundle#24]
Paella bundle is unable to be installed in pumukit 2.2.0 following the instructions in the readme, the error it gives is this:

` user@pumukit:/var/www/pumukit2$ composer require teltek/pmk2-paella-player-bundle
Using version ^1.2 for teltek/pmk2-paella-player-bundle
./composer.json has been updated
Loading composer repositories with package information                             Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for teltek/pmk2-paella-player-bundle ^1.2 -> satisfiable by teltek/pmk2-paella-player-bundle[1.2.0].
    - teltek/pmk2-paella-player-bundle 1.2.0 requires pumukit/pumukit2 >=2.3 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by albacodina** [comment]
Hi @mliradelc,
There are new versions of pumukit in which this bundle can be installed without any problem.

Thank you.
