### ISSUE TITLE
Make config.json dynamic instead of static.

### ISSUE THREAD

**Issue by rubenrua** [teltek/PumukitPaellaPlayerBundle#37]
With a dynamic `config.json` the plugins can be enabled depending of the video.

**Comment by Yurujai** [comment]
Close with https://github.com/teltek/PumukitPaellaPlayerBundle/commit/b018d2b6689403c938348580f095b2e2d082eb97 for PaellaPlayer v7 and PumukitPaellaPlayerBundle v3.0.x or higher
