### ISSUE TITLE
Fullscreen is not supported at IOS Safari

### ISSUE THREAD

**Issue by iriadp** [teltek/PumukitPaellaPlayerBundle#70]
Steps to reproduce it:
- Access a dualstream video using an iPad.
- Try to enable fullscreen mode.

Actual behaviour: It's not possible to put a video on fullscreen using the iPad. The button is missing.
Expected behaviour: To put a video on fullscreen mode using IOS Safari should be possible.

**Comment by rubenrua** [comment]
iOS safari doesn't support Full Screen API:

https://caniuse.com/#feat=fullscreen

We should test `reloadOnFullscreen`.
