### ISSUE TITLE
Improve paella captionsPlugin integration

### ISSUE THREAD

**Issue by Alfro** [teltek/PumukitPaellaPlayerBundle#8]
- The captionsPlugin should not appear if the video has no captions.
- The 'edit button' in the captionsPlugin does not work, it should be fixed or removed.
  ![captionsplugin](https://cloud.githubusercontent.com/assets/11334172/16236628/575241a8-37d9-11e6-889c-cdbfdd829484.png)
- The PaellaRepository generates an array with all types of captions (.srt, .vtt and .dfxp), but only .dfxp is compatible with paella. As a result, some unusable captions are listed in the plugin. (nothing appears) _even though the file is actually a valid .dfxp_
  **Captions:**
  ![captions3](https://cloud.githubusercontent.com/assets/11334172/16236823/00dac1c8-37da-11e6-804d-1c3860533978.png)
  **Result:**
  ![captions2](https://cloud.githubusercontent.com/assets/11334172/16236743/c0a3f836-37d9-11e6-8b53-917738db99b5.png)

**Comment by Yurujai** [comment]
PaellaPlayer v7 supports vtt format. See https://paellaplayer.upv.es/#/doc/captions.md, now new version and plugins works correctly.
